config/routes.rb
Rails.application.routes.draw do
  resources :requests do
    resources :schedules
    resources :spaces
  end
  resources :schedules do
    collection do
      get "remove_all"
    end
    resources :spaces
    
  end
  resources :spaces do 
    resources :schedules
  end
  devise_for :users
  resources :dashboard

  root to: "home#index"

  get "/spaces", to: "spaces#index"

end

app/models/space.rb
class Space < ActiveRecord::Base
	has_many :schedules
	has_many :requests
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :set_space, only: [:show, :edit, :update, :destroy]

  # GET /spaces
  # GET /spaces.json
  def index
    @spaces = Space.all
  end

  # GET /spaces/1
  # GET /spaces/1.json
  def show
  end

  # GET /spaces/new
  def new
    @space = Space.new
  end

  # GET /spaces/1/edit
  def edit
  end

  # POST /spaces
  # POST /spaces.json
  def create
    @space = Space.new(space_params)

    respond_to do |format|
      if @space.save
        format.html { redirect_to @space, notice: 'Space was successfully created.' }
        format.json { render :show, status: :created, location: @space }
      else
        format.html { render :new }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spaces/1
  # PATCH/PUT /spaces/1.json
  def update
    respond_to do |format|
      if @space.update(space_params)
        format.html { redirect_to @space, notice: 'Space was successfully updated.' }
        format.json { render :show, status: :ok, location: @space }
      else
        format.html { render :edit }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spaces/1
  # DELETE /spaces/1.json
  def destroy
    @space.destroy
    respond_to do |format|
      format.html { redirect_to spaces_url, notice: 'Space was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_space
      @space = Space.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def space_params
      params.require(:space).permit(:name, :capacity, :created_at, :update_at, :proyector, :pc, :audio, :reason, :description, :kind, :parking, :numberparking, :other)
    end
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/views/spaces/_form.html.erb
<%= form_for(@space) do |f| %>
  <% if @space.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@space.errors.count, "error") %> prohibited this space from being saved:</h2>

      <ul>
      <% @space.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="col-md-4">

    <div class="field">
    <%= f.label "Nombre" %><br>
    <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <div class="field">
      <%= f.label "Descripción" %><br>
      <%= f.text_area :description, :class => 'form-control' %>
    </div>
    <div class="field">
      <%= f.label "capacidad" %><br>
      <%= f.number_field :capacity, :class => 'form-control' %>
    </div>
    <div class="field">
      <%= f.label "tipo" %><br>
      <%= f.number_field :kind, :class => 'form-control' %>
    </div>

</div>

<div class="col-md-4">
 
   <div class="field">
    <%= f.label "Proyector" %>
    <%= f.check_box :proyector %>
    </div>
    <div class="field">
      <%= f.label "Pc" %>
      <%= f.check_box :pc %>
    </div>
    <div class="field">
      <%= f.label "Audio" %>
      <%= f.check_box :audio %>
    </div>
    <div class="field">
      <%= f.label "Estacionamiento" %>
      <%= f.check_box :parking %>
    </div>
    <div class="field">
      <%= f.label "Cantidad de estacionamiento" %><br>
      <%= f.number_field :numberparking, :class => 'form-control' %>
    </div>
    <div class="field">
      <%= f.label "Otro" %><br>
      <%= f.text_area :other, :class => 'form-control' %>
    </div> 

</div>



  <div class="actions col-md-2 col-md-offset-3 text-center top">
    <%= f.submit class: 'btn btn-success btn-block' %> <br>
    <%= link_to 'Back', spaces_path, :class => 'btn btn-default btn-block' %>
  </div>
<% end %>

app/views/spaces/edit.html.erb
	<%= render "layouts/bar" %>
	<%= render "layouts/dash" %>

<h1>Editing Space</h1>

<%= render 'form' %>

<%= link_to 'Show', @space %> |
<%= link_to 'Back', spaces_path %>

app/views/spaces/index.html.erb
  <%= render "layouts/bar" %>
  <%= render "layouts/dash" %>
<p id="notice"><%= notice %></p>

<div class="container">

<h1>Espacios</h1>

<div class="col-md-10">

<table class="table table-responsive">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Capacidad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spaces.each do |space| %>
      <tr>
        <td><%= space.name %></td>
        <td><%= space.capacity %></td>
        <td><%= link_to 'Mostrar', space %></td>
        <td><%= link_to 'Editar', edit_space_path(space) %></td>
        <td><%= link_to 'Eliminar', space, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Nuevo Espacio', new_space_path %>
</div>

</div>

app/views/spaces/new.html.erb
	<%= render "layouts/bar" %>
	<%= render "layouts/dash" %>
	<div class="col-md-8">
		<h1>New Space</h1>
	</div>


<%= render 'form' %>

app/views/spaces/show.html.erb
  <%= render "layouts/bar" %>
  <%= render "layouts/dash" %>
<p id="notice"><%= notice %></p>

<div class="container">
<table class="table table-responsive">
  <thead>
    <tr>
      <th>Espacio</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td>Nombre</td>
        <td><%= @space.name %></td>
      </tr>
      <tr>
        <td>Creado el</td>
        <td><%= @space.created_at %></td>
      </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_space_path(@space) %> |
<%= link_to 'Back', spaces_path %>	

</div>