config/routes.rb
Rails.application.routes.draw do
  resources :requests do
    resources :schedules
    resources :spaces
  end
  resources :schedules do
    collection do
      get "remove_all"
    end
    resources :spaces
    
  end
  resources :spaces do 
    resources :schedules
  end
  devise_for :users
  resources :dashboard

  root to: "home#index"

  get "/spaces", to: "spaces#index"

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base

	belongs_to :space


end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
    @spaces = Space.all
    @count_schedules = Schedule.count 
    @q = Schedule.ransack(params[:q])
    @events = @q.result(distinct: true)

  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        if @schedule.permanent==true

          duplicated_schedule(@schedule)
          
        end

        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def remove_all
      Schedule.delete_all
      flash[:notice] = "Has borrado todos los resultados"
      redirect_to schedules_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:permanent, :begin, :block1, :block2, :block3, :block4, :block5, :block6, :block7, :block8, :block9, :space_id, :mandated, :mail, :description, :proyector, :pc, :audio, :parking, :numberparking)
    end

    def duplicated_schedule(schedule)
      18.times do |i|
        @new_schedule =@schedule.dup
        #@new_schedule.permanent = false
        @new_schedule.begin = @new_schedule.begin + ((i+1)*7).days
        @new_schedule.save
      end
    end

end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-md-3">
    <div class="field">
      <%= f.label :space_id %><br>
      <%= f.collection_select :space_id, Space.all, :id, :name %>
      </div>
    <div class="field">
      <%= f.label :permanent %><br>
      <%= f.check_box :permanent %>
    </div>
    <div class="field">
      <%= f.label :mandated %><br>
      <%= f.text_field :mandated, :class => 'form-control' %>
    </div>

    <div class="field">
      <%= f.label :mail %><br>
      <%= f.text_field :mail, :class => 'form-control' %>
    </div>
    
  </div>
  <div class="col-md-3">
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description, :class => 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :proyector %>
      <%= f.check_box :proyector %>
      <%= f.label :pc %>
      <%= f.check_box :pc %>
    </div>
    <div class="field">
      <%= f.label :audio %>
      <%= f.check_box :audio %>
      <%= f.label :parking %>
      <%= f.check_box :parking %>
    </div>
    <div class="field">
      <%= f.label :numberparking %><br>
      <%= f.number_field :numberparking, :class => 'form-control' %>
    </div>

  </div>
  <div class="col-md-3">
    

  </div>

  <div class="field">
    <%= f.label :begin %><br>
    <%= f.date_select :begin %>
  </div>
  <div class="field">
    <%= f.label :block1 %>
    <%= f.check_box :block1 %>


    <%= f.label :block2 %>
    <%= f.check_box :block2 %>

    <%= f.label :block3 %>
    <%= f.check_box :block3 %>
  </div>
  <div class="field">
    <%= f.label :block4 %>
    <%= f.check_box :block4 %>

    <%= f.label :block5 %>
    <%= f.check_box :block5 %>

    <%= f.label :block6 %>
    <%= f.check_box :block6 %>
  </div>
  <div class="field">
    <%= f.label :block7 %>
    <%= f.check_box :block7 %>

    <%= f.label :block8 %>
    <%= f.check_box :block8 %>
    
    <%= f.label :block9 %>
    <%= f.check_box :block9 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
  <%= render "layouts/bar" %>
  <%= render "layouts/dash" %>
<h1>Editing Schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/find.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-md-3">
    <div class="field">
      <%= f.label :begin %><br>
      <%= f.collection_select :begin, Schedule.all, :id, :begin %>
    </div>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedules/index.html.erb
  <%= render "layouts/bar" %>
  <%= render "layouts/dash" %>
<p id="notice"><%= notice %></p>

<div class="col-md-10">

<h1>Horarios Totales</h1>

<%= search_form_for @q do |f| %>
  <%= f.label "Sala" %>
  <%= f.search_field :space_name_eq, include_blank: true %>
  <%= f.label "Fecha" %>
  <%= f.select :begin_eq, options_from_collection_for_select(Schedule.all, "begin", "begin", @search), include_blank: true %>
  <%= f.submit  %>
<% end %>
<br>

<div class="col-md-2">
  <br>
  <label for="count">Horarios totales: <span class="badge"><%= @count_schedules %></span></label>

</div>
<div class="col-md-2">
  <%= link_to "Remove All", remove_all_schedules_path, :method => :get, data: { confirm: 'está a punto de borrar todos los datos ¿Está seguro?' }, :class => 'btn btn-danger btn-block' %>
</div>

<div class="col-md-2 col-md-offset-6">
<%= link_to 'Nuevo horario', new_schedule_path, :class => 'btn btn-success btn-block' %>
</div>
<br><br><br>
<table class="table">
  <thead>
    <tr>
      <th>Permanente</th>
      <th>Día</th>
      <th>Encargado</th>
      <th>Mail</th>
      <th>Sala</th>
      <th>Bloques Ocupados</th>

      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @spaces.each do |space| %>
      <% @events.each do |schedule| %>
        <% if space.id == schedule.space.id %>
          <tr>
            <td class="col-md-1"><% if schedule.permanent == true %>
              <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
              <%else%>
              <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
              <% end %>

            </td>
            <td class="col-md-1"><%= schedule.begin.strftime("%m/%d/%Y") %></td>
            <td class="col-md-2"><%= schedule.mandated %></td>
            <td class="col-md-2"><%= schedule.mail %></td>
            <td class="col-md-1"><%= schedule.space.name %></td>
            <td class="col-md-2">
              <% if schedule.block1==true %>
                <span class="badge">1-2</span>
                
              <% end %>
              <% if schedule.block2==true %>
                <span class="badge">3-4</span>
                
              <% end %>
              <% if schedule.block3==true %>
                <span class="badge">5-6</span>
                
              <% end %>
              <% if schedule.block4==true %>
                <span class="badge">7-8</span>
                
              <% end %>
              <% if schedule.block5==true %>
                <span class="badge">9-10</span>
                
              <% end %>
              <% if schedule.block6==true %>
                <span class="badge">11-12</span>
                
              <% end %>
              <% if schedule.block7==true %>
                <span class="badge">13-14</span>
                
              <% end %>
              <% if schedule.block8==true %>
                <span class="badge">15-16</span>
                
              <% end %>
              <% if schedule.block9==true %>
                <span class="badge">17-18</span>
                
              <% end %>

            </td>
            <td class="col-md-1"><%= link_to '', schedule, class: "glyphicon glyphicon-search" %>
            <%= link_to '  ', edit_schedule_path(schedule), class: "glyphicon glyphicon-pencil" %>
            <%= link_to '  ', schedule, method: :delete, data: { confirm: 'Are you sure?' }, class: "glyphicon glyphicon-ban-circle" %></td>
          </tr>
          
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>
</div>

app/views/schedules/new.html.erb
  <%= render "layouts/bar" %>
  <%= render "layouts/dash" %>
<h1>New Schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
  <%= render "layouts/bar" %>
  <%= render "layouts/dash" %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Permanent:</strong>
  <%= @schedule.permanent %>
</p>

<p>
  <strong>Begin:</strong>
  <%= @schedule.begin %>
</p>

<p>
  <strong>Lu12:</strong>
  <%= @schedule.block1 %>
</p>

<p>
  <strong>Lu34:</strong>
  <%= @schedule.block2 %>
</p>

<p>
  <strong>Lu56:</strong>
  <%= @schedule.block3 %>
</p>

<p>
  <strong>Lu78:</strong>
  <%= @schedule.block4 %>
</p>

<p>
  <strong>Lu910:</strong>
  <%= @schedule.block5 %>
</p>

<p>
  <strong>Lu1112:</strong>
  <%= @schedule.block6 %>
</p>

<p>
  <strong>Lu1314:</strong>
  <%= @schedule.block7 %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>