config/routes.rb
Rails.application.routes.draw do
  resources :requests do
    resources :schedules
    resources :spaces
  end
  resources :schedules do
    collection do
      get "remove_all"
    end
    resources :spaces
    
  end
  resources :spaces do 
    resources :schedules
  end
  devise_for :users
  resources :dashboard

  root to: "home#index"

  get "/spaces", to: "spaces#index"

end

app/models/request.rb
class Request < ActiveRecord::Base
	belongs_to :user
	belongs_to :space

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]
  before_action :set_search

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all

  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new

    @request.block1=true
    @request.block2=true
    @request.block3=true
    @request.block4=true
    @request.block5=true
    @request.block6=true
    @request.block7=true
    @request.block8=true
    @request.block9=true
    @year = [params[:q]["begin_eq(1i)"]].reject(&:blank?) unless params[:q].nil?
    @month = [params[:q]["begin_eq(2i)"]].reject(&:blank?) unless params[:q].nil?
    @day = [params[:q]["begin_eq(3i)"]].reject(&:blank?) unless params[:q].nil?
    @space_name= [params[:q][:space_name_eq]].reject(&:blank?) unless params[:q].nil?

    @q = Schedule.search(params[:q])
    @results = @q.result(distinct: true)

    @results.each do |r|

        if r.block1==true 
          @request.block1=false   
        end  
        if r.block2==true 
          @request.block2=false     
        end 
        if r.block3==true 
          @request.block3=false     
        end 
        if r.block4==true 
          @request.block4=false     
        end 
        if r.block5==true 
          @request.block5=false      
        end 
        if r.block6==true 
          @request.block6=false     
        end 
        if r.block7==true 
          @request.block7=false      
        end 
        if r.block8==true 
          @request.block8=false      
        end 
        if r.block9==true 
          @request.block9=false      
        end
    end
   
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def set_search
    @search = Space.search(params[:params])
    @requests = @search.result
    @search.build_condition
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:daterequest, :confirmation, :finishrequest, :permanent, :block1, :block2, :block3, :block4, :block5, :block6, :block7, :block8, :block9, :space_id, :mandated, :mail, :description, :proyector, :pc, :audio, :parking, :numberparking)
    end

    def q_params
      params.require(:q).permit(:begin_eq, :space_name_eq)
    end

    def find_duplicates(q, request)
      find = Schedule.new

      18.times do |i|
        #@q.begin_eq = @q.begin_eq + ((i+1)*7).days
        

        @q = Schedule.where(:begin => find.begin + ((i+1)*7).days, :space_name => find.space_name )

      end
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-3">

    <div class="field">
      <%= f.label :mandated %><br>
      <%= f.text_field :mandated, :class => 'form-control' %>
    </div>

    <div class="field">
      <%= f.label :mail %><br>
      <%= f.text_field :mail, :class => 'form-control' %>
    </div>
    
  </div>
  <div class="col-md-3">
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description, :class => 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :proyector %>
      <%= f.check_box :proyector %>
      <%= f.label :pc %>
      <%= f.check_box :pc %>
    </div>
    <div class="field">
      <%= f.label :audio %>
      <%= f.check_box :audio %>
      <%= f.label :parking %>
      <%= f.check_box :parking %>
    </div>
    <div class="field">
      <%= f.label :numberparking %><br>
      <%= f.number_field :numberparking, :class => 'form-control' %>
    </div>

  </div>
  <div class="col-md-3">
    
  <div class="field">
    <% if @request.block1==true %>
    <% @request.block1=false %>
    <%= f.label :block1 %>
    <%= f.check_box :block1 %>
      
    <% end %>
    
    <% if @request.block2==true %>
    <% @request.block2=false %>
    <%= f.label :block2 %>
    <%= f.check_box :block2 %>
      
    <% end %>
    <% if @request.block3==true %>
    <% @request.block3=false %>
    <%= f.label :block3 %>
    <%= f.check_box :block3 %>
      
    <% end %>   

    </div>

  <div class="field">
    <% if @request.block4==true %>
    <% @request.block4=false %>
    <%= f.label :block4 %>
    <%= f.check_box :block4 %>
      
    <% end %>
    <% if @request.block5==true %>
    <% @request.block5=false %>
    <%= f.label :block5 %>
    <%= f.check_box :block5 %>
      
    <% end %>
    <% if @request.block6==true %>
    <% @request.block6=false %>
    <%= f.label :block6 %>
    <%= f.check_box :block6 %>
      
    <% end %>   

    
  </div>
  <div class="field">
    <% if @request.block7==true %>
    <% @request.block7=false %>
    <%= f.label :block7 %>
    <%= f.check_box :block7 %>

      
    <% end %>
    <% if @request.block8==true %>
    <% @request.block8=false %>
    <%= f.label :block8 %>
    <%= f.check_box :block8 %>
      
    <% end %>
    <% if @request.block9==true %>
    <% @request.block9=false %>
    <%= f.label :block9 %>
    <%= f.check_box :block9 %>
      
    <% end %>
    
  </div>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
  <%= render "layouts/bar" %>
  <%= render "layouts/dash" %>
<h1>Editing Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
  <%= render "layouts/bar" %>
  <%= render "layouts/dash" %>
<p id="notice"><%= notice %></p>

<h1>Listing Requests</h1>

<table>
  <thead>
    <tr>
      <th>Daterequest</th>
      <th>Confirmation</th>
      <th>Finishrequest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.daterequest %></td>
        <td><%= request.confirmation %></td>
        <td><%= request.finishrequest %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
  <%= render "layouts/bar" %>
  <%= render "layouts/dash" %>

<h1>New Request</h1>

<%= search_form_for @q, url: new_request_path do |f| %>
  <%= f.label "Sala" %>
  <%= f.search_field :space_name_eq %>
  <%= f.label "Fecha" %>
  <%= f.date_select :begin_eq %>
  <%= f.submit  %>
<% end %>

<label class="badge"><%= @space_name %></label>
<label class="badge"><%= @year %></label>
<label class="badge"><%= @month %></label>
<label class="badge"><%= @day %></label>

<%= render 'form' %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
  <%= render "layouts/bar" %>
  <%= render "layouts/dash" %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Daterequest:</strong>
  <%= @request.daterequest %>
</p>

<p>
  <strong>Confirmation:</strong>
  <%= @request.confirmation %>
</p>

<p>
  <strong>Finishrequest:</strong>
  <%= @request.finishrequest %>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>